from BaseClasses import ItemClassification

ITEM_NAME_TO_ID = {
    # Artifacts, 1-10
    "Artifact Unlock: Bracelet": 1,
    "Artifact Unlock: Ankh": 2,
    "Artifact Unlock: Urn": 3,
    "Artifact Unlock: Golden Banana": 4,
    "Artifact Unlock: Shield": 5,
    "Artifact Unlock: Chestplate": 6,
    "Artifact Unlock: Golden Treasure": 7,

    # Pack Unlocks (Normal) 11-40
    "Dungeon Row: Late-game Pack 1": 11,
    "Dungeon Row: Late-game Pack 2": 12,
    "Dungeon Row: Mid-tier Pack": 13,
    "Dungeon Row: Speedy Pack 1": 14,
    "Dungeon Row: Speedy Pack 2": 15,
    "Dungeon Row: Gem Pack 1": 16,
    "Dungeon Row: Gem Pack 2": 17,
    "Dungeon Row: Gold Pack 1": 18,
    "Dungeon Row: Gold Pack 2": 19,
    "Dungeon Row: Swag Pack 1": 20,
    "Dungeon Row: Swag Pack 2": 21,
    "Dungeon Row: Tome Pack": 22,
    "Dungeon Row: Skill Pack": 23,
    "Dungeon Row: Control Pack": 24,
    "Dungeon Row: Deck Fixing Pack": 25,
    "Dungeon Row: Vitality Pack 1": 26,
    "Dungeon Row: Vitality Pack 2": 27,
    "Dungeon Row: Basic Monster Pack 1": 28,
    "Dungeon Row: Basic Monster Pack 2": 29,
    "Dungeon Row: Basic Monster Pack 3": 30,
    "Dungeon Row: Hard Monster Pack 1": 31,
    "Dungeon Row: Hard Monster Pack 2": 32,
    "Dungeon Row: Device Pack 1": 33,
    "Dungeon Row: Device Pack 2": 34,
    "Dungeon Row: Device Pack 3": 35,
}


DEFAULT_ITEM_CLASSIFICATIONS = {
    # Artifacts
    "Artifact Unlock: Bracelet": ItemClassification.Progression,
    "Artifact Unlock: Ankh": ItemClassification.Progression,
    "Artifact Unlock: Urn": ItemClassification.Progression,
    "Artifact Unlock: Golden Banana": ItemClassification.Progression,
    "Artifact Unlock: Shield": ItemClassification.Progression,
    "Artifact Unlock: Chestplate": ItemClassification.Progression,
    "Artifact Unlock: Golden Treasure": ItemClassification.Progression,

    # Pack Unlocks (Normal)
    "Dungeon Row: Late-game Pack 1": ItemClassification.Progression,
    "Dungeon Row: Late-game Pack 2": ItemClassification.Progression,
    "Dungeon Row: Mid-tier Pack": ItemClassification.Progression,
    "Dungeon Row: Speedy Pack 1": ItemClassification.Progression,
    "Dungeon Row: Speedy Pack 2": ItemClassification.Progression,
    "Dungeon Row: Gem Pack 1": ItemClassification.Progression,
    "Dungeon Row: Gem Pack 2": ItemClassification.Progression,
    "Dungeon Row: Gold Pack 1": ItemClassification.Progression,
    "Dungeon Row: Gold Pack 2": ItemClassification.Progression,
    "Dungeon Row: Swag Pack 1": ItemClassification.Progression,
    "Dungeon Row: Swag Pack 2": ItemClassification.Progression,
    "Dungeon Row: Tome Pack": ItemClassification.Progression,
    "Dungeon Row: Skill Pack": ItemClassification.Progression,
    "Dungeon Row: Control Pack": ItemClassification.Progression,
    "Dungeon Row: Deck Fixing Pack": ItemClassification.Progression,
    "Dungeon Row: Vitality Pack 1": ItemClassification.Progression,
    "Dungeon Row: Vitality Pack 2": ItemClassification.Progression,
    "Dungeon Row: Basic Monster Pack 1": ItemClassification.Progression,
    "Dungeon Row: Basic Monster Pack 2": ItemClassification.Progression,
    "Dungeon Row: Basic Monster Pack 3": ItemClassification.Progression,
    "Dungeon Row: Hard Monster Pack 1": ItemClassification.Progression,
    "Dungeon Row: Hard Monster Pack 2": ItemClassification.Progression,
    "Dungeon Row: Device Pack 1": ItemClassification.Progression,
    "Dungeon Row: Device Pack 2": ItemClassification.Progression,
    "Dungeon Row: Device Pack 3": ItemClassification.Progression,
}

ITEM_TYPES = {
    "artifact_unlock": [
        "Artifact Unlock: Bracelet",
        "Artifact Unlock: Ankh",
        "Artifact Unlock: Urn",
        "Artifact Unlock: Golden Banana",
        "Artifact Unlock: Shield",
        "Artifact Unlock: Chestplate",
        "Artifact Unlock: Golden Treasure",
    ],
    "dungeon_row_pack_normal": [
        "Dungeon Row: Late-game Pack 1",
        "Dungeon Row: Late-game Pack 2",
        "Dungeon Row: Mid-tier Pack",
        "Dungeon Row: Speedy Pack 1",
        "Dungeon Row: Speedy Pack 2",
        "Dungeon Row: Gem Pack 1",
        "Dungeon Row: Gem Pack 2",
        "Dungeon Row: Gold Pack 1",
        "Dungeon Row: Gold Pack 2",
        "Dungeon Row: Swag Pack 1",
        "Dungeon Row: Swag Pack 2",
        "Dungeon Row: Tome Pack",
        "Dungeon Row: Skill Pack",
        "Dungeon Row: Control Pack",
        "Dungeon Row: Deck Fixing Pack",
        "Dungeon Row: Vitality Pack 1",
        "Dungeon Row: Vitality Pack 2",
        "Dungeon Row: Basic Monster Pack 1",
        "Dungeon Row: Basic Monster Pack 2",
        "Dungeon Row: Basic Monster Pack 3",
        "Dungeon Row: Hard Monster Pack 1",
        "Dungeon Row: Hard Monster Pack 2",
        "Dungeon Row: Device Pack 1",
        "Dungeon Row: Device Pack 2",
        "Dungeon Row: Device Pack 3",
    ],
}

